### ISSUE TITLE
Wrong times for created event

### ISSUE THREAD

**Issue by cameronmcefee** [CoderDojoGitHub/our-dojo#6]
I created an event yesterday via the app and it set the event's times as 7pm-9pm. I created the app somewhere around 6ish, so I could see three feasible problems.
1. Eventbrite is the cause. This would not surprise me
2. Timezone offset issue
3. Timing of the new event is based on when the event is created based on some sort of predictive algorithm. Seems unlikely, but you never know.

**Comment by jonmagic** [comment]
I think I may need a pair partner on this, someone more familiar with what the end event should look like on EventBrite, maybe @cameronmcefee or @brntbeer could pair with me on it in the next few weeks?

Also starting to think I should just put my energy behind doing our own event stuff rather than relying on EventBrite, their system just seems overly complicated for what we are trying to accomplish. I'll try and pull my designer friend in over the next couple of weeks to throw together some mockups so we can get some feedback.

**Comment by brntbeer** [comment]
I'm down! i'll be back in town starting on the 30th of April tho =X

**Comment by jonmagic** [comment]
This shouldn't be an issue anymore now that we are not tied to eventbrite.
